input {
  beats {
    port => 5044
  }
}

filter {
  if [message] {
    json {
      source => "message"
      target => "app"
      skip_on_invalid_json => true
    }
  }

  mutate {
    add_field => {
      "service" => "aiops-risk-predictor"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "aiops-risk-predictor-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}

